version: "3.4"

services:
    client:
        image: client
        build:
            context: client
            dockerfile: ./Dockerfile
        environment:
            NODE_ENV: production
        ports:
            - 5173:5173
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
